language: java
jdk:
- oraclejdk7
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: B0PR5/9lqav6QdkiN6iMEvxc3rc3St6fKEnIt9imMK5ygKz7g/nSloSDn4iJYcP2aBjynHVNCILIbf+0ch8uEo/MuJEUugvaV8OPMC0tV4sjY+3vxgs+ImazKjtYvAK7rgtgyIfu8+ElBxwlO42AktVt7+QUs1rHoPin9PHNqn8=
  file: boilerplate.jar
  skip_cleanup: true
  on:
    repo: BrassGoggledCoders/Boilerplate
    tags: true
    all_branches: true
install: gradle setupCIWorkspace
script: gradle build
